import Head from 'next/head';
import { Inter } from '@next/font/google';
import {BsFillMoonStarsFill, BsSunFill} from 'react-icons/bs';
import { 
  AiFillLinkedin, 
  AiFillYoutube, 
  AiFillGithub 
} from 'react-icons/ai';
import Image from "next/image";
import brianDP from "../public/BLdp.jpeg";
import { useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Brian Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">developedbybrian</h1>
            <ul className="flex items-center">
              <li>
                {darkMode ?
                <BsSunFill 
                  onClick={() => setDarkMode(!darkMode)} 
                  className="cursor-pointer text-2xl"
                  color="white"
                />
                :
                <BsFillMoonStarsFill 
                  onClick={() => setDarkMode(!darkMode)} 
                  className="cursor-pointer text-2xl"
                />
                }
              </li>
              <li>
                <a 
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" 
                  href="https://docs.google.com/document/d/1Mk9GGSmF_Sds0Mbg9ojErhdHZ_dfBW36p4BevMsO-hA/edit?usp=sharing"
                  target="_blank"
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex flex-wrap justify-center">
            <div className="sm:w-4/12 px-4">
              <Image src={brianDP} alt="..." className="shadow-lg rounded-full max-w-full h-auto align-middle border-none" />
            </div>
          </div>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Brian Lee
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Software Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              Welcome to portfolio.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/brianjaebum/" target="_blank" rel="noreferrer">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/jaebum25" target="_blank" rel="noreferrer">
              <AiFillGithub />
            </a>
            <AiFillYoutube />
          </div>
        </section>

        <section>
          <div className="lg:flex gap-10">
            <h3 className="text-3xl py-1">About</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Welcome to the beginning of my development journey!
              I completed my Software Engineering Immersive Bootcamp from 
              <span className="text-teal-500"> General Assembly </span>
              and now I am looking to work as a <span className="text-teal-500"> software devloper</span>. 
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image width={100} height={100} alt="..."/>
              <h3 className="text-lg font-medium py-8 pb-2">Beautiful Designs1</h3>
              <p className="py-2">Enter paragraph here!</p>
              <h4 className="text-teal-600 py-4">design tools!</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">illustrator</p>
              <p className="text-gray-800 py-1">figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image width={100} height={100} alt="..."/>
              <h3 className="text-lg font-medium py-8 pb-2">Beautiful Designs2</h3>
              <p className="py-2">Enter paragraph here!</p>
              <h4 className="text-teal-600 py-4">design tools!</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">illustrator</p>
              <p className="text-gray-800 py-1">figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image width={100} height={100} alt="..."/>
              <h3 className="text-lg font-medium py-8 pb-2">Beautiful Designs3</h3>
              <p className="py-2">Enter paragraph here!</p>
              <h4 className="text-teal-600 py-4">design tools!</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">illustrator</p>
              <p className="text-gray-800 py-1">figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
          <h3 className="text-3xl py-1">Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-800">
              Welcome to the beginning of my development journey!
              I completed my Software Engineering Immersive Bootcamp from 
              <span className="text-teal-500"> General Assembly </span>
              and now I am looking to work as a <span className="text-teal-500"> software devloper</span>. 
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}
